### ISSUE TITLE
ebuild file in Gentoo (linux-4.4.6-gentoo): missing attributes in layout.conf and no valid PORTDIR structure

### ISSUE THREAD

**Issue by kefnab** [zyga/snap-confine-gentoo#1]
The [official installation directions](http://snapcraft.io/docs/core/install) for Gentoo were vague.  So what I attempted as root was:
`cd /opt`
`git clone https://github.com/zyga/snap-confine-gentoo.git`
`cd snap-confine-gentoo`
`ebuild snap-confine-1.0.32.ebuild manifest clean merge`

However, I received these errors:

> Appending / to PORTDIR_OVERLAY...
> !!! Repository 'x-' is missing masters attribute in '/metadata/layout.conf'
> !!! Set 'masters = gentoo' in this file for future compatibility
> ebuild: /opt/snap-confine-gentoo/snap-confine-1.0.32.ebuild: does not seem to have a valid PORTDIR structure

**Comment by zyga** [comment]
Hey!

Thank you for reporting this issue. I need to update the repository with more recent snapd releases but I was starved on time with some recent upstream work. If you'd like to work with me on gentoo packaging (eventually I'd like to propose it for inclusion into the portage tree) then please get in touch with me! (I'm zyga on freenode).

I will look at updating this repository so that you can install snapd and snap-confine but more work is required to make it a nice gentoo package.

**Comment by kefnab** [comment]
I have registered the nick "kefnab" on freenode to discuss, but yes I'm interested.  I am new to both packaging and github, but I have managed to successfully re-package your version of snap-confine (didn't know how to do it properly with a fork, because I had to create a nested series of folders for proper directory structure).

It's best to create one repository for Gentoo, with subfolders for packages, so that portage can do automatic version managing...like [https://github.com/kefnab/kefnab-tools](url)
